### ISSUE TITLE
Defensive player stats

### ISSUE THREAD

**Issue by Darrend1** [rbrnk/fflproject#13]
Defensive TDS or safety's dont seem to get pulled after running livestats.py........Although, running nflgame and pulling stats from a player, i don't think they show up either.

An example would be 1 defensive TD from Kwon Alexander, week 3, TB vs LA

Any hints on where to look next. probably a nflgame issue tho....

**Comment by nickfrerichs** [comment]
This has been added to the develop branch.

**Comment by nickfrerichs** [comment]
It's now part of the latest release.
