### ISSUE TITLE
Chat update

### ISSUE THREAD

**Issue by Darrend1** [rbrnk/fflproject#14]
Since the last update, the chat no longer updates unless the page is refreshed. I know I had a problem with chat in a previous issue report, but not sure where the settings lie now that chat.php has been mostly commented out.

**Comment by nickfrerichs** [comment]
All of the SSE streams have been moved to application/controllers/Sse.php.  There is now a single stream, so if you previously modified the Chat.php controller, I think that's where you'd look.
