### ISSUE TITLE
Create Super Admin not Working

### ISSUE THREAD

**Issue by ObituaryConch** [rbrnk/fflproject#15]
I attempted to install this project and I am unable to create a super admin account. I am using a local MAMP server configuration and I get the following error: 

Not Found

The requested URL /accounts/register was not found on this server.

It definitely is setup correctly with the SQL code and everything is in the root of the htdocs folder. Everytime I go and look for a view or anything to be able to setup the super admin I cannot find anything about it in the code. Am I missing something here?

**Comment by Blyng1** [comment]
This sounds like the rewrite isn't activated. For Mamp see the below link for rewrite settings.
http://stackoverflow.com/questions/7670561/how-to-get-htaccess-to-work-on-mamp.
Bob

**Comment by ObituaryConch** [comment]
Thank you for the information, for some reason MAMP is not liking any of the changes so I will need to do some debugging. Excited for when I can get this project working.

**Comment by ObituaryConch** [comment]
I am now getting the following error after checking all of the .htaccess file rights as well as mod rewrite being active: 

404 Page Not Found

The page you requested was not found.

It now has the nice code ignighter styling which is a positive. 

my htaccess file is as follows: 

RewriteEngine on
RewriteCond $1 !^(index.php?|images|css|js)
RewriteRule ^(.*)$ http://localhost:8888/fflproject/index.php?/$1 [L]

**Comment by Blyng1** [comment]
Looked at some issues involving the mamp server. 
1. Check the .htaccess file sometimes it gets changed to .htaccess.txt.
2. You should make sure that in your /etc/apache2/users/username.conf you have the following:
<Directory "/Users/username/Sites/">
    Options Indexes MultiViews FollowSymlinks
    AllowOverride All
    Order allow,deny
    Allow from all
</Directory>
The FollowSymlinks and AllowOverride are essential here. Maybe you did not configure these correctly in tandem.
Make sure in httpd.conf /private/etc/apache2/extra/httpd-userdir.conf is included as well. It is by default.
After any modifications, restart the web server for the changes to take effect.
1. To debug mod_rewrite you can enable rewrite logging. You should enable that in /etc/apache2/httpd.conf:
   RewriteLogLevel 3
   RewriteLog /path/to/rewrite.log

**Comment by Blyng1** [comment]
This link has a tool that is out on git to test .htaccess and the rewrite mod to see if they are working.
https://docs.bolt.cm/3.0/howto/making-sure-htaccess-works

**Comment by nickfrerichs** [comment]
This seems like a configuration issue with the web server.  I'm going to close it.  Thanks for helping Bob!
