### ISSUE TITLE
Charger players showing as free agents

### ISSUE THREAD

**Issue by Boblyng** [rbrnk/fflproject#18]
This is a nflgame data issue. After recent player updates all the former SD players show nfl_team_id=0 instead of 8. I went in to the database and changed the chargers Team abbrev to LAC from SD. I did a test and changed Philip Rivers back to nfl_team_id=8 in the database then reran the player update and it changed Rivers back to  nfl_team_id=0.

What am I missing. I will check the nflgame page and see if I see anything there.

**Comment by Boblyng** [comment]
I fixed the issue by editing the nflgame/__init__.py file

**Comment by nickfrerichs** [comment]
Thanks Bob, I'm going to leave this open until nflgame is updated just in case someone else could use the help.

**Comment by nickfrerichs** [comment]
Closing, season is well underway...
