### ISSUE TITLE
Step 1 installation issue?

### ISSUE THREAD

**Issue by bubbajones69** [rbrnk/fflproject#20]
Hi - 
I have completed the instructions for installation and now get the init page and link to create super user.  When I click this however, I receive an error indicating:

Not Found
The requested URL /fflproject/accounts/register was not found on this server.

Any advice on what I have done incorrectly is appreciated!

thx
Brandon

**Comment by Boblyng** [comment]
Brandon looks like you are using IIS server? Do you have url rewrite installed? Sounds like you aren't getting redirected correctly.

Bob

**Comment by bubbajones69** [comment]
I have it setup in linux using apache - I've got rewrite enabled (i put fflproject in the root so changed my .htaccess to add that - something wrong with the index.php rewrite - if i manually put it in the url it works - just can't figure out what I have misconfigured....

**Comment by bubbajones69** [comment]
If I manually change the URL after the 404 and add 'index.php' I can get the page to load properly...
so sort of works, but annoying having to enter index.php after every click...

I've verified the rewrite module is enabled... (you can see my server settings at: 

http://104.198.224.12/info.php

Loaded Modules | core mod_so http_core mod_access_compat mod_actions mod_alias mod_allowmethods mod_auth_basic mod_auth_digest mod_authn_anon mod_authn_core mod_authn_dbd mod_authn_dbm mod_authn_file mod_authn_socache mod_authz_core mod_authz_dbd mod_authz_dbm mod_authz_groupfile mod_authz_host mod_authz_owner mod_authz_user mod_autoindex mod_cache mod_cache_disk mod_data mod_dbd mod_deflate mod_dir mod_dumpio mod_echo mod_env mod_expires mod_ext_filter mod_filter mod_headers mod_include mod_info mod_log_config mod_logio mod_mime_magic mod_mime mod_negotiation mod_remoteip mod_reqtimeout mod_rewrite mod_setenvif mod_slotmem_plain mod_slotmem_shm mod_socache_dbm mod_socache_memcache mod_socache_shmcb mod_status mod_substitute mod_suexec mod_unique_id mod_unixd mod_userdir mod_version mod_vhost_alias mod_dav mod_dav_fs mod_dav_lock mod_lua prefork mod_proxy mod_lbmethod_bybusyness mod_lbmethod_byrequests mod_lbmethod_bytraffic mod_lbmethod_heartbeat mod_proxy_ajp mod_proxy_balancer mod_proxy_connect mod_proxy_express mod_proxy_fcgi mod_proxy_fdpass mod_proxy_ftp mod_proxy_http mod_proxy_scgi mod_proxy_wstunnel mod_systemd mod_cgi mod_php5
-- | --

**Comment by bubbajones69** [comment]
Figured it out - httpd.conf needed "allowoverride All" -

Brandon
