### ISSUE TITLE
Stupid question - Step one - suppressing php warnings

### ISSUE THREAD

**Issue by bubbajones69** [rbrnk/fflproject#21]
I think I successfully got step one complete - but I can't seem to get the php warning to stop showing....
at the top of each page I've got these warning boxes that keep showing up - I've changed my php.ini file to turn off logging - my config.php file has log level set to 1 - (I've tried 0, 4 always same output) . Anyone have suggestions?

thx
Brandon

A PHP Error was encountered
Severity: Warning

Message: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.

Filename: helpers/fflproject_helper.php

Line Number: 33

**Comment by nickfrerichs** [comment]
FYI, rather than suppress php warnings, it's best to set your timezone by editing your php.ini file and assigning a value to date.timezone.  http://php.net/manual/en/timezones.php

**Comment by bubbajones69** [comment]
Thx finally sorted it out - restarting httpd wasn't picking up the php.ini
settings - once I restarted the server it fixed it and then just updated my
pho MySQL to get rid of the mismatch warnings - all seems good with the
world now :-)

Does the NFLgmae db keep track of player season stats ?  I am working on
phone app for the league and would be cool to show without linking to NFL
web page

Brandon
