### ISSUE TITLE
update.py -players exception - Leno, Charles, Jr.

### ISSUE THREAD

**Issue by bubbajones69** [rbrnk/fflproject#29]
keep getting problem running update.py -players

I've tried running multiple times but always same record - is this something to be concerned with?

python update.py -players
Loading games for REG 2017 week 3
Downloading team rosters...
32/32 complete. (100.00%)
Done!

There were some errors during the download. Usually this is a
result of an HTTP request timing out, which means the
resulting "players.json" file is probably missing some data.
An appropriate solution is to re-run the script until there
are no more errors (or when the errors are problems on 
NFL.com side.)
-------------------------------------------------------------------------------
Could not get player info from roster row:

<tr class="even">
<td>72</td>
<td style="text-align:left"> <a href="/player/charleslenojr./2550169/profile">Leno, Charles, Jr.</a></td>
<td>OT</td>
<td>ACT</td>
<td> 6'3"</td>
<td>306</td>
<td>10/9/1991</td>
<td>4</td>
<td>Boise State</td></tr>

Exception:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nflgame/update_players.py", line 419, in run
    roster.append(meta_from_soup_row(team, row))
  File "/usr/lib/python2.7/site-packages/nflgame/update_players.py", line 179, in meta_from_soup_row
    last_name, first_name = map(lambda s: s.strip(), name.split(','))
ValueError: too many values to unpack

Updating local FF database....
Added: 0 players.
Updated: 7660 players.
Completed 2017-09-23 00:55:19.054504

**Comment by nickfrerichs** [comment]
As you can see in the traceback, this error is coming from nflgame, not my code.  If you look/ask on that project site he can probably provide an answer.  Though the error text already pretty well explains the situation: An appropriate solution is to re-run the script until there
are no more errors

**Comment by nickfrerichs** [comment]
I checked and I'm seeing this error too.  Here you go: https://github.com/BurntSushi/nflgame/issues/316
