### ISSUE TITLE
Not seeing lineups when viewing games in progress or historical games

### ISSUE THREAD

**Issue by bubbajones69** [rbrnk/fflproject#32]
I've added some screen shots - but can't see the starters.  If I go into admin mode - I can see them - 

<img width="624" alt="screenshot 2017-09-25 21 41 36" src="https://user-images.githubusercontent.com/18621147/30838580-61b3e0a8-a23a-11e7-991b-2b6dbd0b7d91.png">

<img width="1349" alt="screenshot 2017-09-25 21 43 32" src="https://user-images.githubusercontent.com/18621147/30838621-9b89416a-a23a-11e7-9139-695e2d794867.png">
<img width="613" alt="screenshot 2017-09-25 21 44 39" src="https://user-images.githubusercontent.com/18621147/30838650-d11afd82-a23a-11e7-8b70-096dd5b00f7c.png">

0.0001 | SELECT GET_LOCK('407b0fa5c8cc25a27199e152d0b229b36cfd1d0d', 300) AS ci_session_lock
-- | --
0.0002 | SELECT `data`FROM `ci_sessions`WHERE `id` = '407b0fa5c8cc25a27199e152d0b229b36cfd1d0d'
0.0004 | SELECT *FROM `user_accounts`JOIN `user_login_sessions` ON `user_accounts`.`uacc_id` = `user_login_sessions`.`usess_uacc_fk`WHERE `user_accounts`.`uacc_id` = '1'AND `user_accounts`.`uacc_active` = 1AND `user_accounts`.`uacc_suspend` =0AND `user_login_sessions`.`usess_token` = '8c3ab2314c50592af38cafa256f22d6087c2b9f2'AND `user_login_sessions`.`usess_login_date` > '2017-09-25 19:44:22'
0.0016 | UPDATE `user_login_sessions` SET `user_login_sessions`.`usess_login_date` = '2017-09-25 21:44:22'WHERE `user_login_sessions`.`usess_uacc_fk` = '1'AND `user_login_sessions`.`usess_token` = '8c3ab2314c50592af38cafa256f22d6087c2b9f2'
0.0009 | select player.id as player_id, player.first_name, player.last_name, player.nfl_position_id, player.short_name, nfl_position.text_id as pos_text, IFNULL(nfl_team.club_id,"FA") as club_id, IFNULL(sum(fantasy_statistic.points),0) as points from `roster` join `player` on `roster`.`player_id` = `player`.`id` join nfl_position on nfl_position.id = player.nfl_position_id left join nfl_team on nfl_team.id = player.nfl_team_id left join fantasy_statistic on fantasy_statistic.player_id = roster.player_id and fantasy_statistic.year = 2017 and fantasy_statistic.league_id = roster.league_id where `roster`.`player_id` not in (SELECT `player_id` FROM `starter` where `week` = 3 and `year` = 2017 and team_id = 7) and `roster`.`league_id` = 1 and roster.team_id = 7  group by roster.player_id order by nfl_position.display_order asc
0.0001 | SELECT `season_year`FROM `league`WHERE `id` = '1'
0.0001 | SELECT `nfl_season`FROM `league_settings`WHERE `league_id` = '1'
0.0030 | SELECT `eid`, `week`, `year`, UNIX_TIMESTAMP(start_time) as startFROM `nfl_schedule`WHERE `start_time` < '2017-09-25 21:44:22'AND `gt` = 'REG'AND `year` = '2017'ORDER BY `start_time` DESC LIMIT 1
0.0025 | SELECT `eid`, `week`, `year`, UNIX_TIMESTAMP(start_time) as startFROM `nfl_schedule`WHERE `start_time` > '2017-09-25 21:44:22'AND `year` = '2017'ORDER BY `start_time` ASC LIMIT 1
0.0002 | SELECT max(year) as yFROM `position`WHERE `position`.`league_id` = '1'AND `year` <= '2017'
0.0002 | SELECT `position`.`id`, `position`.`nfl_position_id_list`, `position`.`text_id`, `position`.`max_roster`, `position`.`min_roster`, `position`.`max_start`, `position`.`min_start`FROM `position`WHERE `league_id` = '1'AND `year` = '2017'ORDER BY `display_order` ASC
0.0006 | SELECT `starter`.`starting_position_id`, `player`.`id` as `player_id`, `player`.`first_name`, `player`.`last_name`, `player`.`short_name`, nfl_position.short_text as pos_text, IFNULL(nfl_team.club_id, "FA") as club_id, IFNULL(sum(fantasy_statistic.points), 0) as points, team_keeper.id IS NOT NULL as keeperFROM `starter`JOIN `player` ON `player`.`id` = `starter`.`player_id`JOIN `nfl_position` ON `nfl_position`.`id` = `player`.`nfl_position_id`LEFT JOIN `nfl_team` ON `nfl_team`.`id` = `player`.`nfl_team_id`LEFT JOIN `fantasy_statistic` ON `fantasy_statistic`.`player_id` = `starter`.`player_id` and `fantasy_statistic`.`year` = 2017 and `fantasy_statistic`.`league_id` = `starter`.`league_id`LEFT JOIN `team_keeper` ON `team_keeper`.`team_id` = 1 and `team_keeper`.`year`=2017 and `team_keeper`.`player_id`=`player`.`id`WHERE `starter`.`year` = '2017'AND `starter`.`week` = '3'AND `starter`.`team_id` = '7'GROUP BY `starter`.`player_id`ORDER BY `starter`.`id` ASC
0.0005 | SELECT `home`.`id` as `home_id`, `away`.`id` as `away_id`, `schedule`.`week`, `home`.`team_name` as `home_name`, `away`.`team_name` as `away_name`, `home_result`.`team_score` as `home_score`, `away_result`.`team_score` as `away_score`, `home_result`.`win` as `home_win`, `home_result`.`loss` as `home_loss`, `home_result`.`tie` as `home_tie`, `away_result`.`win` as `away_win`, `away_result`.`loss` as `away_loss`, `away_result`.`tie` as `away_tie`FROM `schedule`JOIN `team` as `home` ON `home`.`id` = `schedule`.`home_team_id`JOIN `team` as `away` ON `away`.`id` = `away_team_id`LEFT JOIN `schedule_result` as `home_result` ON `home_result`.`schedule_id` = `schedule`.`id` and `home_result`.`team_id` = `schedule`.`home_team_id`LEFT JOIN `schedule_result` as `away_result` ON `away_result`.`schedule_id` = `schedule`.`id` and `away_result`.`team_id` = `schedule`.`away_team_id`WHERE `schedule`.`year` = '2017'AND (`schedule`.`home_team_id` = 7 or `schedule`.`away_team_id` = 7)ORDER BY `schedule`.`week` ASC
0.0002 | SELECT `club_id`FROM `nfl_team`WHERE `club_id` != 'NONE'
0.0028 | SELECT `h`, `v`, UNIX_TIMESTAMP(start_time) as start_timeFROM `nfl_schedule`WHERE `week` = '3'AND `year` = '2017'AND `gt` = 'REG'
0.0026 | SELECT `h`, `v`, `week`FROM `nfl_schedule`WHERE `year` = '2017'AND `gt` = 'REG'
0.0003 | SELECT distinct(club_id) as club_idFROM `nfl_team`WHERE `club_id` != 'NONE'
0.0020 | SELECT max(week) as weekFROM `nfl_schedule`WHERE `year` = '2017'AND `gt` = 'REG'
0.0003 | SELECT sum(schedule_result.team_score) as points, sum(schedule_result.opp_score) as opp_points, sum(win=1) as wins, sum(loss=1) as losses, sum(tie=1) as ties, count(schedule_result.id) as total_games, ((sum(win=1) + (sum(tie=1)/2))/count(schedule_result.id)) as winpctFROM `schedule_result`JOIN `schedule` ON `schedule`.`id` = `schedule_result`.`schedule_id`WHERE `team_id` = '7'AND `schedule`.`year` = '2017'
0.0003 | SELECT `team`.`id` as `team_id`, `team`.`owner_id`, `team`.`long_name`, `team`.`logo`, `team`.`team_name` as `team_name`, `division`.`name` as `division_name`, `owner`.`first_name`, `owner`.`last_name`, `owner`.`phone_number`FROM `team`JOIN `owner` ON `team`.`owner_id` = `owner`.`id`LEFT JOIN `team_division` ON `team_division`.`team_id` = `team`.`id` and `team_division`.`year` = 2017LEFT JOIN `division` ON `team_division`.`division_id` = `division`.`id`WHERE `team`.`league_id` = '1'AND `team`.`id` = '7'ORDER BY `team_name` ASC
0.0003 | SELECT `menu_item`.`text` as `item_text`, `menu_bar`.`text` as `menu_text`, `menu_item`.`url`, `menu_bar`.`url` as `bar_url`FROM `menu_bar`LEFT JOIN `menu_item` ON `menu_bar`.`id` = `menu_item`.`menu_bar_id`WHERE `menu_bar`.`admin` =0AND `menu_bar`.`super_admin` =0AND `menu_bar`.`hide` =0AND `menu_item`.`hide` =0ORDER BY `menu_bar`.`super_admin` DESC, `menu_bar`.`order` ASC, `menu_item`.`order` ASC

**Comment by nickfrerichs** [comment]
What do you see under the non-live scores for that week?  In the menu: 2017 Season > Weekly Scores

**Comment by bubbajones69** [comment]
<img width="884" alt="screenshot 2017-09-26 14 02 57" src="https://user-images.githubusercontent.com/18621147/30876081-839e5b88-a2c3-11e7-8bd6-148b1c3aec42.png">

here is associated sql from debug

0.0002 | SELECT GET_LOCK('ed4dae08955392df9ceee616512066ac6df268ad', 300) AS ci_session_lock
-- | --
0.0003 | SELECT `data`FROM `ci_sessions`WHERE `id` = 'ed4dae08955392df9ceee616512066ac6df268ad'
0.0005 | SELECT *FROM `user_accounts`JOIN `user_login_sessions` ON `user_accounts`.`uacc_id` = `user_login_sessions`.`usess_uacc_fk`WHERE `user_accounts`.`uacc_id` = '1'AND `user_accounts`.`uacc_active` = 1AND `user_accounts`.`uacc_suspend` =0AND `user_login_sessions`.`usess_token` = '2e29c7ff48f38806fda0b249bcd172747a1eb58c'AND `user_login_sessions`.`usess_login_date` > '2017-09-26 12:02:41'
0.0021 | UPDATE `user_login_sessions` SET `user_login_sessions`.`usess_login_date` = '2017-09-26 14:02:41'WHERE `user_login_sessions`.`usess_uacc_fk` = '1'AND `user_login_sessions`.`usess_token` = '2e29c7ff48f38806fda0b249bcd172747a1eb58c'
0.0003 | SELECT max(year) as yFROM `position`WHERE `position`.`league_id` = '1'AND `year` <= '2017'
0.0002 | SELECT `position`.`text_id`, `position`.`max_start`, `position`.`id`FROM `position`WHERE `league_id` = '1'AND `year` = '2017'ORDER BY `display_order` ASC
0.0017 | SELECT `player`.`id` as `player_id`, `player`.`short_name`, `player`.`photo`, `player`.`number`, `starter`.`team_id`, `starter`.`starting_position_id`, `nfl_team`.`club_id`, `nfl_position`.`short_text` as `nfl_pos`, `nfl_position`.`type` as `nfl_pos_type`, IFNULL(sum(fs.points), "-") as pointsFROM `starter`JOIN `player` ON `player`.`id` = `starter`.`player_id`LEFT JOIN `nfl_team` ON `nfl_team`.`id` = `player`.`nfl_team_id`LEFT JOIN `nfl_position` ON `nfl_position`.`id` = `player`.`nfl_position_id`LEFT JOIN `fantasy_statistic_week` as `fs` ON `fs`.`player_id` = `player`.`id` and `fs`.`year` = 2017 and `fs`.`week`=2 and `fs`.`league_id` = 1WHERE `starter`.`year` = '2017'AND `starter`.`week` = '2'AND `starter`.`league_id` = '1'GROUP BY `player`.`id`
0.0003 | SELECT `team`.`id`, `team`.`team_name`FROM `team`WHERE `league_id` = '1'
0.0004 | SELECT `home_team_id` as `home_id`, `away_team_id` as `away_id`, `game`, `home`.`team_name` as `home_name`, `away`.`team_name` as `away_name`FROM `schedule`JOIN `team` as `home` ON `home`.`id` = `home_team_id`LEFT JOIN `team` as `away` ON `away`.`id` = `away_team_id`WHERE `year` = '2017'AND `week` = '2'AND `schedule`.`league_id` = '1'ORDER BY `game` ASC
0.0003 | SELECT distinct(week) as weekFROM `schedule`WHERE `league_id` = '1'AND `year` = '2017'ORDER BY `week` ASC
0.0005 | SELECT `menu_item`.`text` as `item_text`, `menu_bar`.`text` as `menu_text`, `menu_item`.`url`, `menu_bar`.`url` as `bar_url`FROM `menu_bar`LEFT JOIN `menu_item` ON `menu_bar`.`id` = `menu_item`.`menu_bar_id`WHERE `menu_bar`.`admin` =0AND `menu_bar`.`super_admin` =0AND `menu_bar`.`hide` =0AND `menu_item`.`hide` =0ORDER BY `menu_bar`.`super_admin` DESC, `menu_bar`.`order` ASC, `menu_item`.`order` ASC

**Comment by nickfrerichs** [comment]
Have you run `python update.py -stats_summary` as described in the wiki?

**Comment by bubbajones69** [comment]
Yes - several times and even specified specific week

**Comment by bubbajones69** [comment]
One thing I have noticed is on another instance I have installed which is working as expected, when I display "League" -> "Players" there are 7 columns, the final being TEAM.  In the instance that isn't working properly, there is another column RANK which has value of 999.0 for all players - could I somehow have an older version installed?

**Comment by bubbajones69** [comment]
ISSUE FOUND - If the Position specifications for the league have "Start Max" as "No Min" - the rosters don't show up - changing these to 1 for each position corrected views.

Maybe permanent fix is to change to default to 1 and just remove "No Min" as option?
