### ISSUE TITLE
Error when running update.py -players

### ISSUE THREAD

**Issue by bryarwagner** [rbrnk/fflproject#35]
When I run the update.py script with the option -players, I receive this error:

![image](https://user-images.githubusercontent.com/33761663/34317423-e56cf276-e773-11e7-9ef2-6f5bdd45a702.png)

I have checked any possible permission that could be involved, and have been running it as root to see if I can run it, but cannot.

Any other option I give update.py runs flawlessly. I have gone through the depths of the internet trying to see if this is a generic problem but it doesn't seem to be. Thanks in advance!

**Comment by nickfrerichs** [comment]
What is the PLAYER_UPDATE_CMD set to in ./python/config.py ?

For troubleshooting, add this prior to the subprocess.call on line 270 in ./python/update.py
`print c.PLAYER_UPDATE_CMD`

Then run it and see what command is outputted, you should be able to paste that command and run it without errors, if you still get a permissions error it's something outside of fflproject code.

**Comment by bryarwagner** [comment]
PLAYER_UPDATE_CMD is appropriately set to ./python2.7/dist-packages/nflgame/update_players.py

When I run this command on its own, it updates all NFL Rosters and checks for any missing players with no errors (after fixing the JR issue with Charles Leno Jr)

I have checked subprocess.py and checked its permissions and they are set to 755.

**Comment by nickfrerichs** [comment]
Try creating a new file ex: test.py with the following contents:

```
import subprocess

cmd = './python2.7/dist-packages/nflgame/update_players.py'
subprocess.call(cmd.split(' '))
```


If you run that, do you get the same error?

**Comment by bryarwagner** [comment]
Yes I got the exact same error.

**Comment by nickfrerichs** [comment]
It must be an issue with the server config or permissions rather than fflproject code.  Do you have SELinux enforcing? Are you running python in a virtualenv?

Maybe you could try an even simpler test:

```
import subprocess

cmd = 'ls'
subprocess.call(cmd.split(' '))
```

**Comment by bryarwagner** [comment]
![image](https://user-images.githubusercontent.com/33761663/34895252-84744c98-f7aa-11e7-87fe-f86da14efe3b.png)

This is what I got when I ran what you suggested.

**Comment by nickfrerichs** [comment]
This still seems like a permissions issue on your system. You get the same permission error with the python script that just calls update_players.py so I'm going to close this as it's not really an issue with fflproject.

Two things you could try:
- In my config.py, I use /usr/bin/nflgame-update-players that gets installed with nflgame, you might try that rather than directly calling the python file.

- Or explicitly specify the path to python in your cmd: /usr/bin/python <path to update_players.py>

**Comment by bryarwagner** [comment]
After much more sifting through the internet and looking at BurntSushi's nflgame GitHub, I found the I needed to set the PLAYER_UPDATE_CMD needed to be set to : /usr/local/bin/nflgame-update-players

Was just a matter of figuring out where everything was installed I guess, thanks for the help!

**Comment by Boblyng** [comment]
Yeah in Deb7 it is /usr/local/bin/nflgame-update-players by default for me also.
