### ISSUE TITLE
Can't Stay Logged In

### ISSUE THREAD

**Issue by thindery** [rbrnk/fflproject#36]
I'm having an issue with a user staying logged in. For example, after they get the join leage invite URL, they create an account and login. After login session data doesn't seem to persist.

Any tips or suggestions greatly appreciated!

**Comment by nickfrerichs** [comment]
It's only one user having the issue? I'd have them try another computer that you know works to see if it's something with their machine/browser or the account. Or even just have them try a different browser on the same machine. Do they have cookies enabled? This sounds like what might happen if you didn't.

**Comment by thindery** [comment]
It's only me for my testing. Cookies are set. It could be because I'm debugging between multiple Chrome browsers and incognito. Not sure. I think it might be a bug with Flexi Auth and newer Code Igniter. Seems Flexi auth is clearing session data and the multiple ajax requests that get hit may be related. Not entirely sure at the moment. In any case, working on porting everything to updated Code Igniter and implementing Ion Auth

**Comment by nickfrerichs** [comment]
I can take a look when I go through the changes this off season.  Does it happen with already established accounts or just during the new user sign up part?  Then can you give me the steps to reproduce it?  Ex: have two accounts logged in in chrome, one using incognito mode.

**Comment by nickfrerichs** [comment]
Just a heads up, I'm not sure if this would resolve the issue or not, but I'm in the process of moving to Ion Auth. It should be one of the updates ahead of the 2018 season.

**Comment by nickfrerichs** [comment]
I moved to Ion Auth in the development branch, expect these changes to make their way to the master branch before the 2018 season starts. I can't say for sure that it will resolve your issues, you can create a new issue if it's still not fixed.
