### ISSUE TITLE
IR Slot

### ISSUE THREAD

**Issue by bryarwagner** [rbrnk/fflproject#37]
What files would I need to edit in order to add in an IR slot under the Bench view for My Team/Roster ?

**Comment by Boblyng** [comment]
We have a keeper league and are going to allow 2 ir slots for players that get season ending injuries.  Was looking to maintain roster limit rules at 15 plus up to 2 ir spots. Was waiting for the off season to play around with adding it.

**Comment by nickfrerichs** [comment]
I'd suggest looking at how Codeigniter works, since that's what the site is built on. Adding the slot will be editing a view/controller/model file combination and you'd likely need to modify the database as well. Then the same in the admin location if you want it to be part of the admin options.
