### ISSUE TITLE
Defensive Scoring

### ISSUE THREAD

**Issue by bryarwagner** [rbrnk/fflproject#38]
In my league, one of the new rules passed this offseason was adding negative points to Team Defense when they give up 30+ points. 
-1pt 30-39
-2pt 40+

In the Scoring Definitions, under D_ST, there is an Away Team Score, and under team Offense there is a Home Score. How can I go about making this work without getting to crazy?

**Comment by Boblyng** [comment]
We give our defenses 14 points before the game starts and based on points allowed and yards allowed it gets reduced and even goes into the negatives. I will have to look at the scoring when I get home and see how we did it.

**Comment by nickfrerichs** [comment]
My league doesn't use the "range" scoring, but I think that's what you'd use.

- So add a definition and choose "Unit range"
- Click "Add another range" to have two ranges to edit
- Click "Edit Values"
- For one, set the range start to 30, end to 39 and points to -1 
- For the other, set the range start to 40, end to 999 (or whatever you feel is high enough) and points to -2

So 0-29 points will be 0 points (wasn't defined)
30-39 points will be -1
40+ points will be -2
