### ISSUE TITLE
Issue on update.py

### ISSUE THREAD

**Issue by bryarwagner** [rbrnk/fflproject#42]
While trying to run the update.py script, I receive the follow error. And I have tried it with all the different variables to no avail. Not sure it's a me error or a script error, thought I'd post it here for more research.

![image](https://user-images.githubusercontent.com/33761663/42175817-6e850c1a-7dec-11e8-95e2-0a5582860add.png)

**Comment by nickfrerichs** [comment]
This looks to be an issue with nflgame decoding the json data. Is it still throwing an error for you? I'm wondering if the NFL feed was having issues at the time you tried.

When I run the same command I get no errors. I was able to import the 2018 schedule with python update.py -schedule -year 2018 -weektype reg -week all

**Comment by bryarwagner** [comment]
I meant to respond on this sooner, my issue was resolved once I uninstalled and reinstalled nflgame
