### ISSUE TITLE
Developement cut Tade button issue 

### ISSUE THREAD

**Issue by Boblyng** [rbrnk/fflproject#43]
I just updated my development area to the latest Development cut and the trade button visually doesn't appear to do anything when pushed. After I manually refresh I do see the trade. 
Installed on Debian 7

**Comment by nickfrerichs** [comment]
Thanks Bob, I'm combing back through things again after merging the new CSS and some new javascript. I'll make sure to take a look when I get to that page.

**Comment by nickfrerichs** [comment]
This should be resolved now. You should see a popup notice for whichever step of the trade process you just completed.
