### ISSUE TITLE
Join League Page issue

### ISSUE THREAD

**Issue by bryarwagner** [rbrnk/fflproject#44]
Good Morning, 

Just wanted to let you know of an issue with the new push. When going to the Join League page this is what I get:

![image](https://user-images.githubusercontent.com/33761663/44220166-d3a19000-a14b-11e8-90c5-2a0465c2f400.png)

So far the other pages I've gone to appear to be fine.

**Comment by Boblyng** [comment]
Bryar I am not see that. Did you run the db_upgrade.py? It seems like the css isn't being recognized.
![join](https://user-images.githubusercontent.com/12156055/44220741-1a3fbc00-a145-11e8-9186-c425eddf0a46.jpg)

**Comment by bryarwagner** [comment]
I ran db_upgrade.py and it came back with database is already version 1.4

![image](https://user-images.githubusercontent.com/33761663/44221115-75c27780-a14e-11e8-8675-a3a9bd5ff20c.png)

**Comment by Boblyng** [comment]
You should be on 1.6

**Comment by bryarwagner** [comment]
Lol! Oh boy... thats a problem then. Why would it not be recognizing the new database?

**Comment by Boblyng** [comment]
![myl](https://user-images.githubusercontent.com/12156055/44221781-25481b80-a148-11e8-8d0c-d0a7fca1681b.jpg)

**Comment by Boblyng** [comment]
Does your db_upgrade.py file look like the one in the link?
https://github.com/nickfrerichs/fflproject/blob/master/python/db_upgrade.py

**Comment by bryarwagner** [comment]
It did not, turns out I kept transferring over the wrong file for that. But, now Im having a new issue where I try and login and it just goes back to the login screen without actually logging me in.

**Comment by bryarwagner** [comment]
And as soon as I say that, it lets me login, I am good now, thanks for the help!

**Comment by Boblyng** [comment]
No problem good luck with your upcoming season.
