### ISSUE TITLE
Cant reset season / year

### ISSUE THREAD

**Issue by bubbajones69** [rbrnk/fflproject#49]
Hi - 
Having trouble getting system to update for 2018 season.  I've tried a few things but best I've done is change to 2017 postseason.  right now update.py -hello returns Year 2017 week 17 week type REG

**Comment by bryarwagner** [comment]
I’ve been having this issue, and upon researching, I have found it is more than likely a problem with NFLGame. There is an open issue ticket where someone made a change to the nflgame-update-sched script and it fixed the problem.

**Comment by bryarwagner** [comment]
https://github.com/BurntSushi/nflgame/issues/363

Scroll down a little ways to a post from ochawkeye and at the bottom of his post he shows the path to fix the file and what and where to edit.

**Comment by bubbajones69** [comment]
thx!

**Comment by nickfrerichs** [comment]
Here's what I did.

In the file live.py, temporarily add this URL on line 68 after the old one.

_CUR_SCHEDULE = "http://www.nfl.com/liveupdate/scorestrip/ss.xml"
_CUR_SCHEDULE = "http://www.nfl.com/ajax/scorestrip?season=2018&seasonType=REG&week=1"

**Comment by bryarwagner** [comment]
Just thought I would add this in after doing more searching. NFLGAME from BurntSushi is no longer maintained, but a group of people have picked it up and forked off of it and designed it as a drop in replacement for nflgame. I just installed it on my system after uninstall the original nflgame and my issue with not being about to get to season 2018 went away immediately. If you want to try it, nflgame-redux is the name of it. 

https://github.com/derek-adair/nflgame

**Comment by Boblyng** [comment]
Bry,
Did you use the following commands or variation of those commands to do that?
pip uninstall nflgame 
pip install nflgame-redux
Did you need to do anything else?
Going to test this in my development area and want to make sure I don't miss anything.
Thanks
Bob

**Comment by bryarwagner** [comment]
Yes, I ran those two commands with success. 

I then went and ran the update.py -schedule to make sure it came up 2018 week1, and also ran update.py -players a couple times (most errors went away, but couldn't pull data for Ced Wilson)

I was then able to go on the site, admin, and end 2017 season. The site then gave me the option to start 2018 season. 

The nflgame-redux uses all the same commands as nflgame as it's the same nflgame, just now maintained and issues are being worked on again. 

Hope all works well for you. 

Bryar

**Comment by nickfrerichs** [comment]
Sweet thanks, I'll switch over to the new nflgame-redux once things settle down.

**Comment by bubbajones69** [comment]
did you find a way past the "sound not find gsis_id for : Ced Wilson?  the -players is tough to see if it got everyone - I ran once, said it updated etc, ran again and then it added 4 more players

trying to see if way to determine if it got everything
