### ISSUE TITLE
no way for user to switch between leagues

### ISSUE THREAD

**Issue by bubbajones69** [rbrnk/fflproject#52]
I have 1.60 mostly working however ran into issue with joining more than one league - can't find way to toggle between leagues - in 1.40 I remember there being a toggle at the bottom - but now user is "stuck" in most recently joined league.

Any ideas?

**Comment by nickfrerichs** [comment]
Yeah, I didn't implement the javascript to change leagues when I switched frameworks over the offseason. I'll try to get to it soon, maybe later today.

**Comment by nickfrerichs** [comment]
You can now switch leagues under League > Switch Leagues
