### ISSUE TITLE
Quick Stat for kickers Heading issue

### ISSUE THREAD

**Issue by Boblyng** [rbrnk/fflproject#55]
On the quick stat popup for kickers it is missing a header title for xp's made.
![quickstat](https://user-images.githubusercontent.com/12156055/46098936-14e58080-c18b-11e8-8aa0-1bb2c0c2cf14.jpg)

**Comment by nickfrerichs** [comment]
This is now fixed in the latest update.

**Comment by nickfrerichs** [comment]
Bob, you might double check you have the right category, or maybe there are two that are the same. In my league I use kicking_xpmade, this one was kicking_xptot. Both come from the NFL feed and maybe they are the same so it won't matter. Better to have too many stats available than not enough I guess.
