### ISSUE TITLE
player database inaccuracies

### ISSUE THREAD

**Issue by bubbajones69** [rbrnk/fflproject#56]
This is probably an issue with nflgame - but the player database has some inconsistencies... for example, data feed claims Phillip Sims is a QB for Seattle, is ACT and status 1, however, his profile page http://www.nfl.com/player/phillipsims/2553780/gamelogs shows no game stats and he isn't really on their roster.  His jersey number is also "0" - He is now a coach of a college team and was waived by the Seahawks in 2016 - odd thing is the date_updated for him in my db is 2018-08-04 20:58:19.

**Comment by Boblyng** [comment]
That is strange. I show him as having no team not active and last updated 2016-06-07 02:49:29.
![sims](https://user-images.githubusercontent.com/12156055/46423868-37344c80-c6fd-11e8-8107-a9cebdd48647.jpg)

**Comment by bubbajones69** [comment]
do you still get an issue when you run update.py -players related to Wilson?  I wonder if my db update isn't completing properly because of that issue

-------------------------------------------------------------------------------
Could not get GSIS id at http://www.nfl.com/player/cedwilson/2560936/profile
-------------------------------------------------------------------------------
Could not find gsis_id for {'status': u'RES', 'last_name': u'Wilson', 'weight': 197, 'profile_id': 2560936, 'number': 16, 'height': 74, 'college': u'Bowie State', 'full_name': u'Ced Wilson', 'first_name': u'Ced', 'years_pro': 0, 'birthdate': u'3/10/1995', 'team': 'DAL', 'position': u'WR', 'profile_url': 'http://www.nfl.com/player/cedwilson/2560936/profile'}
Updating local FF database....

**Comment by Boblyng** [comment]
Yes that is the only error I get.

**Comment by Boblyng** [comment]
That error only means it couldn't be found on NFL.com it doesn't end the update process at that point.

**Comment by bubbajones69** [comment]
well - I tried building a new database - when you create the ffl database, the Phillip Simms record is added and shows active - running update.py -players doesn't change it -

I ran: mysql -u root -p fflproject <fflproject.sql

checked player table and the record is there from the start - anybody have any ideas?

**Comment by nickfrerichs** [comment]
I think I see what's going on and have added a fix. The active status was being set with whatever nflgame returned. But if there are cases where a player drops out of nflgame and is not first marked active, they could end up in this situation.

I've added a last_seen column to the player table. Once a player's last_seen date is older than 30 days, the player update script will mark them as inactive. I picked 30 days arbitrarily just in case there's some flapping of players in nflgame, but if you want to force a player to drop off, just set their last_seen date as 30+ days ago.

Run db_upgrade.py when you pull the latest version.

**Comment by bubbajones69** [comment]
Thanks - I cleaned up by setting everyone inactive then updated and seems
to correct it
