### ISSUE TITLE
Please help with some error messages

### ISSUE THREAD

**Issue by jrpost7** [rbrnk/fflproject#7]
I have changed the config-example.php to config.php and added my db information and i get these errors. Please help

A PHP Error was encountered

Severity: Warning

Message: mysqli::real_connect(): (28000/1045): Access denied for user 'jrpost7'@'ip-107-180-54-253.ip.secureserver.net' (using password: YES)

Filename: mysqli/mysqli_driver.php

Line Number: 202

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home/jrpost77/public_html/system/core/Exceptions.php:272)

Filename: core/Common.php

Line Number: 568

A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: core/MY_Controller.php

Line Number: 141

**Comment by nickfrerichs** [comment]
This seems like an authentication error being reported by your MySQL server.  Make sure the your username/password is correct.  Also make sure you have granted permissions, from the error it looks like you're not using localhost.  If permissions are only granted for that user on the localhost, it won't work.

 To troubleshoot, try connecting to the sql server from your webserver with the same username/password.  mysql -u jrpost7 -p -h <sql server>
