### ISSUE TITLE
Player photos

### ISSUE THREAD

**Issue by Darrend1** [rbrnk/fflproject#9]
Are the player photos working with the normal install method? or are there any extra steps. Before I go digging into the script :)

**Comment by nickfrerichs** [comment]
Out of the box, if you run `update.py -players -photos` it will set player photos to the included generic photos in `images/nfl` based on the players team.  

If you want custom players photos, copy `python/player_photo-example.py` to `python/player_photo.py` and write your own code to retrieve and store a photo in `images/player` for the player and return the filename (without path).
